apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-2
  labels:
    app: k8s-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service-2
  template:
    metadata:
      labels:
        app: k8s-service-2
    spec:
      imagePullSecrets:
        - name: jannusuraj-registry-secret
      containers:
        - name: k8s-service-2
          image: jannusuraj/k8s-service-2:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: K8S_SERVICE_1_URL
              value: http://k8s-service-1:8080
          envFrom:
            - configMapRef:
                name: message-configmap