apiVersion: v1
kind: Service
metadata:
  name: k8s-service-2
spec:
  selector:
    app: k8s-service-2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  sessionAffinity: None
  type: LoadBalancer